# Generated by Django 3.2.16 on 2023-02-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20230212_2053'),
        ('readingGroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
