# Generated by Django 3.2.16 on 2023-02-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingGroup', '0004_rename_book_readinggroup_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinggroup',
            old_name='book_id',
            new_name='book',
        ),
    ]
