# Generated by Django 3.2.16 on 2023-02-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20230212_2053'),
        ('readingGroup', '0005_rename_book_id_readinggroup_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
